# Generated by Django 4.0.6 on 2022-07-20 20:08

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email adress')),
                ('login_type', models.CharField(choices=[('KakaoLogin', 'KakaoLogin'), ('SiteLogin', 'SiteLogin')], max_length=30, verbose_name='login_type')),
                ('nickname', models.CharField(max_length=30, null=True, verbose_name='nickname')),
                ('username', models.CharField(max_length=30, null=True, verbose_name='username')),
                ('contact_num', models.CharField(max_length=50, null=True, verbose_name='contact_num')),
                ('location', models.CharField(max_length=50, null=True, verbose_name='location')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is_staff')),
                ('profile_image_url', models.CharField(max_length=200, null=True, verbose_name='profile_image_url')),
                ('profile_image_storage_path', models.CharField(max_length=200, null=True, verbose_name='profile_image_storage_path')),
                ('kakao_id', models.PositiveIntegerField(null=True, verbose_name='kakao_id')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
