# Generated by Django 4.0.6 on 2022-07-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='contact_num'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kakao_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='kakao_id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image_storage_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='profile_image_storage_path'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='profile_image_url'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='username'),
        ),
    ]
