# Generated by Django 4.0.6 on 2022-11-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_contact_num_alter_user_kakao_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sms_check_char', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sms_auth',
            },
        ),
    ]
