# Generated by Django 4.0.6 on 2022-11-29 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_sms_check_char_smsauth_sms_check_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsauth',
            old_name='phone_number',
            new_name='contact_num',
        ),
    ]
