# Generated by Django 4.0.6 on 2022-08-19 20:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QAndA',
            new_name='QnA',
        ),
        migrations.RenameModel(
            old_name='QAndAComment',
            new_name='QnAComment',
        ),
        migrations.AlterModelTable(
            name='qna',
            table='QnAs',
        ),
        migrations.AlterModelTable(
            name='qnacomment',
            table='QnA_comments',
        ),
    ]
