# Generated by Django 4.0.6 on 2022-08-19 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_rename_q_and_a_qnacomment_qna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnacomment',
            name='qna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_comments', to='announcements.qna'),
        ),
    ]
