# Generated by Django 4.0.6 on 2022-09-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='img1_s3_path',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='img1_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
