# Generated by Django 4.0.6 on 2022-07-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeorder',
            name='want_delivery_date',
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cafeorder',
            name='product_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_confirmed', 'not_confirmed'), ('confirmed', 'confirmed'), ("can't_cancel", "can't_cancel"), ('completed', 'completed')], default='not_confirmed', max_length=50),
        ),
        migrations.AlterField(
            model_name='packageorder',
            name='is_packaging',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
