# Generated by Django 4.0.6 on 2022-07-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_cakeorder_count_cakeorder_product_delete_orderedcake'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageorder',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
