# Generated by Django 4.0.6 on 2022-08-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('not_confirmed', 'not_confirmed'), ('confirmed', 'confirmed'), ("can't_cancel", "can't_cancel"), ('completed', 'completed')], default='not_confirmed', max_length=50),
        ),
    ]
