# Generated by Django 4.0.6 on 2022-08-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeorder',
            name='cafe_location',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cafeorder',
            name='cafe_owner_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cafeorder',
            name='cafename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cafeorder',
            name='corporate_registration_num',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='additional_explanation',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='packageorder',
            name='delivery_location',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='packageorder',
            name='is_packaging',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='packageorder',
            name='purpose',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
