# Generated by Django 4.0.6 on 2022-08-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_review_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='img_s3_path',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='img_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
