# Generated by Django 4.0.6 on 2022-08-29 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_review_img_s3_path_review_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
