# Generated by Django 4.0.6 on 2022-09-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
