# Generated by Django 4.0.6 on 2022-07-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='independentimage',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
