# Generated by Django 4.0.6 on 2022-07-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_independentimage_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='independentimage',
            old_name='image_url',
            new_name='img_src',
        ),
        migrations.RenameField(
            model_name='packageimage',
            old_name='image_url',
            new_name='img_src',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='image_url',
            new_name='img_src',
        ),
    ]
