# Generated by Django 4.0.6 on 2022-09-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productimage_img_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageimage',
            name='package',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='img_src',
            new_name='img_url',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='place',
        ),
        migrations.AddField(
            model_name='productimage',
            name='property',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='s3_path',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='PackageImage',
        ),
    ]
